version: '3'
services:
  redis:
    restart: always
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379

  web-app:
    restart: always
    image: nurbolot02/spring-boot-docker
    container_name: web2
    ports:
      - 8080:8080
    volumes:
      - .:/program
    
