FROM ubuntu
RUN apt update

RUN apt install openjdk-17-jre -y
RUN apt install maven -y
WORKDIR /program/demo
COPY . .

RUN mvn clean
RUN mvn install
RUN mv ./target/spring-redis-mvn-0.0.1-SNAPSHOT.jar ../
WORKDIR /program
RUN rm -rf ./demo
CMD java -jar ./spring-redis-mvn-0.0.1-SNAPSHOT.jar
